# Generated by Django 2.1.2 on 2018-11-23 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
