# Generated by Django 2.1.2 on 2018-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_file', '0002_auto_20181123_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
