# Generated by Django 2.1.2 on 2018-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='owner',
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
