# Generated by Django 2.1.3 on 2018-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20181121_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_update_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5sum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='part_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
