# Generated by Django 2.1.3 on 2018-11-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_file', '0003_auto_20181121_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='part_no',
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='last_update_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5sum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='name_path',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
