# Generated by Django 2.1.3 on 2018-11-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20181121_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
