# Generated by Django 2.1.3 on 2018-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user_name_path',
            field=models.TextField(default='admin', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
