# Generated by Django 2.1.3 on 2018-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0007_auto_20181122_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_name_path',
            field=models.CharField(max_length=1023, primary_key=True, serialize=False),
        ),
    ]
